#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'


def options(opt):
	grp = opt.add_option_group('CL_DLL options')

	grp.add_option('--disable-cldll', action = 'store_true', dest = 'NO_CLDLL', default = False,
		help = 'disable cl_dll build [default: %(default)s]')


def configure(conf):
	conf.env.NO_CLDLL = conf.options.NO_CLDLL
	conf.define('WIN32', 1)

	if conf.options.NO_CLDLL:
		return


def build(bld):

	source = bld.path.ant_glob(['*.cpp'])

	includes = [ '.' , '../common' , '../pm_shared' , '../public']

	bld.shlib(
		source   = source,
		target   = 'cl_dll',
		features = 'cxx',
		includes = includes,
		rpath    = bld.env.DEFAULT_RPATH,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
