#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'


def options(opt):
	grp = opt.add_option_group('DLL options')

	grp.add_option('--disable-dll', action = 'store_true', dest = 'NO_DLL', default = True,
		help = 'disable game dll build [default: %(default)s]')


def configure(conf):
	conf.env.NO_DLL = conf.options.NO_DLL
	conf.define('WIN32', 1)

	if conf.options.NO_DLL:
		return


def build(bld):

	if bld.env.NO_DLL:
		return

	source = bld.path.ant_glob(['*.cpp'])
	

	includes = [ '.' , '../common' , '../pm_shared' , '../public', '../engine']

	bld.shlib(
		source   = source,
		target   = 'ib',
		features = 'cxx',
		includes = includes,
		rpath    = bld.env.DEFAULT_RPATH,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
