#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
from waflib.extras import pthread
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('Engine options')

	grp.add_option('--enable-fbdev', action = 'store_true', dest = 'FBDEV_SW', default = False,
		help = 'build fbdev-only software-only engine')

	grp.add_option('--disable-async-resolve', action = 'store_true', dest = 'NO_ASYNC_RESOLVE', default = False,
		help = 'disable multithreaded operations(asynchronous name resolution)')

	grp.add_option('--enable-custom-swap', action = 'store_true', dest = 'CUSTOM_SWAP', default = False,
		help = 'enable custom swap allocator. For devices with no swap support')

	grp.add_option('--enable-legacy-sdl', action = 'store_true', dest = 'SDL12', default = False,
		help = 'enable using SDL1.2 instead of SDL2(not recommended) [default: %default]')

	grp.add_option('--enable-static-binary', action = 'store_true', dest = 'STATIC', default = False,
		help = 'build static binary(not recommended, --single-binary required) [default: %default]')

	grp.add_option('--enable-engine-tests', action = 'store_true', dest = 'ENGINE_TESTS', default = False,
		help = 'embed tests into the engine, jump into them by -runtests command line switch [default: %default]')

	grp.add_option('--enable-engine-fuzz', action = 'store_true', dest = 'ENGINE_FUZZ', default = False,
		help = 'add LLVM libFuzzer [default: %default]' )

	opt.load('sdl2')
	
def configure(conf):
	# check for dedicated server build
	if conf.options.DEDICATED:
		conf.define('IB_DEDICATED', 1)
	else:
		conf.load('sdl2')
		if not conf.env.HAVE_SDL2:
			conf.fatal('SDL2 not available! If you want to build dedicated server, specify --dedicated')
		conf.define('IB_SDL', 2)

	if conf.options.STATIC:
		conf.env.STATIC = True
		conf.define('IB_NO_LIBDL',1)

	if not conf.env.DEST_OS in ['win32', 'android'] and not conf.options.NO_ASYNC_RESOLVE:
		conf.check_pthreads(mode='c')

	if hasattr(conf.options, 'DLLEMU'):
		conf.define_cond('IB_DLL_LOADER', conf.options.DLLEMU)

	if conf.env.MAGX:
		conf.define('IB_CRASHHANDLER', 0)

	conf.env.ENGINE_TESTS = conf.options.ENGINE_TESTS

	if conf.options.ENGINE_FUZZ:
		conf.env.append_unique('CFLAGS', '-fsanitize=fuzzer-no-link')
		conf.env.append_unique('LINKFLAGS', '-fsanitize=fuzzer')

	conf.define_cond('IB_ENGINE_TESTS', conf.env.ENGINE_TESTS)
	conf.define_cond('IB_STATIC_LIBS', conf.env.STATIC_LINKING)
	conf.define_cond('IB_CUSTOM_SWAP', conf.options.CUSTOM_SWAP)
	conf.define_cond('IB_ENABLE_MAIN', conf.env.DISABLE_LAUNCHER)
	conf.define_cond('IB_NO_ASYNC_NS_RESOLVE', conf.options.NO_ASYNC_RESOLVE)
	conf.define_cond('SUPPORT_BSP2_FORMAT', conf.options.SUPPORT_BSP2_FORMAT)
	conf.define_cond('IB_64BIT', conf.env.DEST_SIZEOF_VOID_P != 4)
	conf.define_cond('DBGHELP', conf.env.DEST_OS == 'win32')
	conf.define_cond('PSAPI_VERSION', conf.env.DEST_OS == 'win32') # will be defined as 1

	for refdll in conf.refdlls:
		refdll.register_define(conf)

def build(bld):
	# public includes for renderers and utils use
	bld(name = 'engine_includes', export_includes = '. core')

	is_cxx_link = False
	libs = [ 'engine_includes', 'public' ]

	# basic build: dedicated only
	source = bld.path.ant_glob([
		'core/*.c'])

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32', 'SHELL32', 'GDI32', 'ADVAPI32', 'DBGHELP', 'PSAPI', 'WS2_32' ]
		source += bld.path.ant_glob(['platform/win32/*.c'])


	if bld.env.HAVE_SDL2:
		libs.append('SDL2')


	includes = []

	install_path = bld.env.LIBDIR
	features = ['c', 'cxxshlib' if is_cxx_link else 'cshlib']
	
	bld(source   = source,
		target   = 'iron-barons-core',
		features = features,
		includes = includes,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		rpath = bld.env.DEFAULT_RPATH,
	)
